Catch by reference, not by value
GCC 8 emits:

cardcomm/pkcs11/src/cardlayer/cardpluginbeid/beidcard.cpp:223:21: error: catching polymorphic type ‘class eIDMW::CMWException’ by value [-Werror=catch-value=]
  catch(CMWException e)

This is because call-by-value may need to run a copy constructor, which
is complicated for a polymorphic type.

Rather than catching by value, catch by reference instead, which avoids
copy constructors entirely.